parameters:
    mailer_transport: 'smtp'
    mailer_host: '127.0.0.1'
    mailer_port: 1025
    mailer_user: null
    mailer_password: null
    
    
monolog:
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
            max_files: 10
        console:
            type:   console
            bubble: false
            channels: [!event, !doctrine]
