framework:
    esi:
        enabled: true
  session:
    name: "ALPIXEL_SESSID"
    handler_id: ~
    save_path: "%kernel.root_dir%/../var/sessions"
  translator:
    fallback: ["%default_locale%"]

swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    port: '%mailer_port%'
    spool:
        type: memory

doctrine:
    dbal:
        connections:
            default:
                driver:   pdo_mysql
                host:     "%database_host%"
                unix_socket: ~
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  utf8mb4

stof_doctrine_extensions:
  default_locale: 'fr_FR'
  orm:
    default:
      timestampable: true
      sluggable: true
      sortable: true


<% if (bundles['bundlesCustom'].indexOf('alpixel/menu-bundle') !== -1) { %>#Menu and breadcrumbs
knp_menu:
    twig:
        template: AlpixelMenuBundle:blocks:menu.html.twig
    templating: false
    default_renderer: twig<% } %>

<% if (bundles['bundlesCustom'].indexOf('alpixel/seobundle') !== -1) { %>sonata_seo:
  page:
    title: "ALPIXEL - Symfony"
    metas:
      name:
        description: ""

seo:
  sitemap_base_url: "%url_production%"<% } %>

<% if (bundles['bundlesCustom'].indexOf('alpixel/mediabundle') !== -1) { %>liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%alpixel_media.upload_folder%"
                cache_prefix: "filters"
    filter_sets:
        cache: ~
        admin:
            quality: 100
            filters:
                auto_rotate: ~
                thumbnail: { size: [140, 93], mode: outbound }<% } %>

<% if (isMultilingual) { %>jms_translation:
  locales: '%enabled_locales%'
  source-language: '%default_locale%'
  configs:
    app:
      dirs: ['%kernel.root_dir%', '%kernel.root_dir%/../src']
      output_dir: '%kernel.root_dir%/Resources/translations'
      ignored_domains: ['SonataAdminBundle', 'CMSBundle']
      excluded_names: ["*TestCase.php", "*Test.php", "*Admin.php"]
      excluded_dirs: ["cache", "data", "logs"]
      extractors: ['jms_i18n_routing']

jms_i18n_routing:
  default_locale: '%default_locale%'
  locales: '%enabled_locales%'
  strategy: 'prefix'

lunetics_locale:
  allowed_locales: '%enabled_locales%'
  guessing_order: ['query', 'router', 'session', 'browser']<% } %>

imports:
  - { resource: 'parameters.yml' }
  - { resource: 'security.yml' }
  - { resource: 'services.yml' }
  <% if (bundles['bundlesCustom'].indexOf('alpixel/cmsbundle') !== -1) { %>- { resource: 'cms.yml' }<% } %>
  <% if (bundles['bundlesCustom'].indexOf('friendsofsymfony/elastica-bundle') !== -1) { %>- { resource: 'elastica.yml' }<% } %>
  <% if (bundles['bundlesCustom'].indexOf('sonata-project') !== -1) { %>- { resource: 'admin.yml' }<% } %>

<% if (bundles['bundlesCustom'].indexOf('alpixel/userbundle') !== -1) { %>fos_user:
  db_driver: 'orm'
  firewall_name: 'main'
  user_class: 'AppBundle\Entity\User'<% } %>

twig:
  exception_controller:  'alpixel_cms.exception_controller:showAction'
  globals:
      base_url: "%url_production%"
  <% if (bundles['bundlesCustom'].indexOf('alpixel/mediabundle') !== -1) { %>form:
      resources:
          - 'AlpixelMediaBundle:Form:fields.html.twig'
          - 'layout/form.html.twig'<% } %>
  paths:
    - "%kernel.root_dir%/Resources/themes/%theme%/views/"
    <% if (bundles['bundlesCustom'].indexOf('sonata-project') !== -1) { %>- "%kernel.root_dir%/Resources/themes/admin/views/"<% } %>


<% if (bundles['bundlesCustom'].indexOf('alpixel/cmsbundle') !== -1) { %>
ivory_ck_editor:
    plugins:
        fileuploader:
            path:     "/bundles/alpixelmedia/fileuploader/"
            filename: "plugin.js"
    configs:
        admin:
            toolbar: "admin_bar"
            format_tags: 'p;h1;h2;h3;pre'
            filebrowserUploadRoute: 'upload_wysiwyg'
            allowedContent: true
            disallowedContent: 'script; *[on*]'
            extraPlugins: 'fileuploader'
            contentsCss: 'css/wysiwyg.min.css'
    toolbars:
        configs:
            admin_bar:
                - "@basicsStyles"
                - "-"
                - "@paragraph"
                - "/"
                - "@styles"
                - "-"
                - "@links"
                - "/"
                - "@clipboard"
                - "-"
                - "@upload"
        items:
            clipboard:      [ "Source", "-", "Save" ]
            basicsStyles:    [ 'Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat' ]
            paragraph:      [ 'NumberedList','BulletedList','-','Outdent','Indent','-','Blockquote','CreateDiv', '-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock','-','BidiLtr','BidiRtl','-','Table' ]
            links:          [ 'Link','Unlink','Anchor' ]
            insert:         [ 'Image','Flash','Table','HorizontalRule','Smiley','SpecialChar','PageBreak','Iframe' ]
            styles:         [ 'Styles','Format','Font','FontSize' ]
            colors:         [ 'TextColor','BGColor' ]
            upload:         [ 'Uploader' ]
