# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # OS X
      host_ram = `sysctl hw.memsize | awk '{print $2/1048576}'`.to_i
      host_cpus = `sysctl hw.logicalcpu | awk '{print $2}'`.to_i

      # Linux
      if host_ram == 0 && host_cpus == 0
        host_ram = `grep ^MemTotal /proc/meminfo 2>/dev/null | awk '{print $2 / 1024}'`.to_i
        host_cpus = `grep ^processor /proc/cpuinfo 2>/dev/null | wc -l`.to_i
      end

      if host_ram > 0 && host_cpus > 0
        vb.customize ["modifyvm", :id, "--cpus", host_cpus / 2, "--memory", host_ram / 3, "--ioapic", "on"]
      else
        # Fallback if the sysctl values are unavailable
        vb.customize ["modifyvm", :id, "--cpus", "2", "--memory", 2048, "--ioapic", "on"]
      end
    end

    config.vm.box = "ALPIXEL/symfony"
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.hostname = "<%= appname %>.local"
    config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }
end
