
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # OS X      host_cpus = `sysctl hw.logicalcpu | awk '{print $2}'`.to_i

      host_cpus = `sysctl hw.logicalcpu | awk '{print $2}'`.to_i

      # Linux
      if host_cpus == 0
        host_cpus = `grep ^processor /proc/cpuinfo 2>/dev/null | wc -l`.to_i
      end

      config.vm.provider "virtualbox" do |vb|
        if host_cpus > 0
          vb.customize ["modifyvm", :id, "--cpus", host_cpus / 2, "--memory", 4096, "--ioapic", "on"]
        else
          vb.customize ["modifyvm", :id, "--cpus", "2", "--memory", 4096, "--ioapic", "on"]
        end
      end

    config.ssh.username = "vagrant"
    config.ssh.password = "vagrant"
    config.vm.box = "ALPIXEL/symfony"
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.hostname = "devbox.local"
    config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }
    #config.vm.synced_folder ".", "/var/www"
end
